spring:
  profiles:
    active: mysql
#  batch:
#    job:
#      names: ${job.name:NONE}
#      // --job.name=thirdJob
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: embedded
---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/BATCH_APP?useUnicode=true&characterEncoding=utf8
      username: root
      password: abcd5511
      driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
    job:
      names: DbCursorConfig
#      names: ${job.name:NONE}
      # enable false
      enabled: true
      # table prefix
#      tablePrefix: SYSTEM_
      tablePrefix: BATCH_